### ISSUE TITLE
三元 vs if else

### ISSUE THREAD

**Issue by menciusKael** [creeperyang/blog#48]
// 第一种 三元运算
            customer_type.length ? customer_type.forEach(item => {
                $('select[name="question-lever"]').append('<option value=' + item.id + '>' + item.value + '</option>')
            }) : $('select[name="performance-income"]').append('<option value="">暂无数据</option>')

 // 第二种 if else
            if (customer_type.length) {
                $('select[name="question-lever"]').append('<option value=' + item.id + '>' + item.value + '</option>')
            }else{
                $('select[name="performance-income"]').append('<option value="">暂无数据</option>')
            }

有几个问题想请教下
1. 像这种$('select[name="question-lever"]').append('<option value=' + item.id + '>' + item.value + '</option>')比较多的操作适合三目运算吗？

2. 三目运算和if else谁的性能更好点？

**Comment by creeperyang** [comment]
1. 个人爱好，你的例子我更喜欢 if/else；
2. 无所谓性能谁更好，性能瓶颈也不会出现在这里。

另外，这个repo的话请不要提issue...
